# Borrowing the latest-sidecar image to extract the datacollector binaries
FROM lacework/datacollector:latest-sidecar AS lacework
RUN cp /var/lib/lacework-backup/*/datacollector > datacollector_linux

# Borrowing latest alpine for ca-certificates
FROM alpine:latest AS alpine
RUN apk -U --no-cache add ca-certificates

# Build a fresh scratch image
FROM scratch

# Add SSL certs
RUN mkdir -p /etc/ssl/certs/
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Prep and copy lacework agent
RUN mkdir -p /var/log/lacework /var/lib/lacework/config
COPY --from=lacework /datacollector_linux /var/lib/lacework/datacollector
RUN chmod +x /var/lib/lacework/datacollector

# Copy entrypoint script
COPY examplecorp-entrypoint.sh /examplecorp-entrypoint.sh
RUN chmod +x /examplecorp-entrypoint.sh
