FROM examplecorp-base-alpine:latest

RUN apk -U --no-cache add nginx

RUN rm -rf /etc/nginx/*
RUN rm -rf /usr/share/nginx
EXPOSE 80
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh

ENTRYPOINT ["/examplecorp-entrypoint.sh", "nginx-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
